name: autofix.ci

on:
  pull_request:
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Convert to WebP
        id: convert
        run: |
          sudo apt-get -y install webp
          pip install webp-converter
          cd hud-resources
          WEBP_OUTPUT="$(webpc -q=75 --r)"
          echo "$WEBP_OUTPUT" | grep -q "NOT convert" | ( ! grep -q "Converted files count: 0" )
          echo "$WEBP_OUTPUT"
      - name: Compress WebP
        id: compress
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          webpQuality: '90'
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
